-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

module AbsGramm where

type Loc = (Int, Int)
type Ident = String

newtype PTrue = PTrue (Loc,Ident)
  deriving (Eq, Ord, Show, Read)

newtype PFalse = PFalse (Loc,Ident)
  deriving (Eq, Ord, Show, Read)

newtype PReturn = PReturn (Loc,Ident)
  deriving (Eq, Ord, Show, Read)

newtype PNull = PNull (Loc,Ident)
  deriving (Eq, Ord, Show, Read)

newtype PIdent = PIdent (Loc,Ident)
  deriving (Eq, Ord, Show, Read)

newtype PFloat = PFloat (Loc,Ident)
  deriving (Eq, Ord, Show, Read)

newtype PInteger = PInteger (Loc,Ident)
  deriving (Eq, Ord, Show, Read)

newtype PString = PString (Loc,Ident)
  deriving (Eq, Ord, Show, Read)

newtype PChar = PChar (Loc,Ident)
  deriving (Eq, Ord, Show, Read)

data Program = Prog [Declaration]
  deriving (Eq, Ord, Show, Read)

data TypeSpec
    = TSimple SType | TPointer TypeSpec | TArray TypeSpec PInteger
  deriving (Ord, Show, Read)

instance Eq TypeSpec where
  (==) (TSimple typ1) (TSimple typ2) = typ1 == typ2 
  (==) (TPointer typ1) (TPointer typ2) = typ1 == typ2
  (==) (TArray typ1 (PInteger (_,ident1))) (TArray typ2 (PInteger (_,ident2))) = ident1 == ident2 && typ1 == typ2
  (==) _ _ = False

data SType
    = SType_Float
    | SType_Int
    | SType_Char
    | SType_String
    | SType_Bool
    | TypeError
    | TypeVoid
  deriving (Eq, Ord, Show, Read)

data Declaration
    = DefVar PIdent TypeSpec Exp
    | DecVar PIdent TypeSpec
    | DefFun PIdent [ParamClause] TypeSpec Block
    | DefFunInLine PIdent [ParamClause] TypeSpec Exp
  deriving (Eq, Ord, Show, Read)

data ParamClause = PArg [Arg]
  deriving (Eq, Ord, Show, Read)

data Arg = DArg PIdent TypeSpec
  deriving (Eq, Ord, Show, Read)

data Block = DBlock [Stm]
  deriving (Eq, Ord, Show, Read)

--SReturnTyped Stm TypeSpec

data Stm
    = SDecl Declaration
    | SBlock Block
    | SAssign LExp Exp
    | SWhile Exp Stm
    | SIfElse Exp Stm Stm
    | SReturn PReturn
    | SReturnExp PReturn Exp
    | SProcCall PIdent [Params]
    -- Tipizzare solo i return.
  deriving (Eq, Ord, Show, Read)

data Params = ParExp [Exp]
  deriving (Eq, Ord, Show, Read)

data Op
    = Or
    | And
    | Less
    | LessEq
    | Greater
    | GreaterEq
    | Equal
    | NotEq
    | Plus
    | Minus
    | Prod
    | Div
    | Mod
    | Pow
  deriving (Eq, Ord, Show, Read)

data Exp
    = ENot Exp
    | ENeg Exp
    | ELExp LExp
    | EDeref LExp
    | EInt PInteger
    | EFloat PFloat
    | EChar PChar
    | EString PString
    | ETrue PTrue
    | EFalse PFalse
    | ENull PNull
    | EArray [Exp]
    | EFunCall PIdent [Params]
    | EOp Exp Op Exp
    | ETyped Exp TypeSpec Loc
  deriving (Eq, Ord, Show, Read)

data LExp
    = LRef LExp
    | LArr LExp Exp
    | LIdent PIdent
    -- La prima è la loc la seconda è la dloc.
    | LExpTyped LExp TypeSpec Loc Loc
  deriving (Eq, Ord, Show, Read)


class Typed a where
  getType :: a -> TypeSpec
  getLoc :: a -> Loc
  isTypeError :: a -> Bool

-- ETyped Exp TypeSpec Integer Integer
instance Typed Exp where
    getType (ETyped _ typ _ ) = typ
    getLoc (ETyped _ _ loc) = loc
    isTypeError texp = getType texp == (TSimple TypeError)


-- StmTyped Stm TypeSpec
{-
instance Typed Stm where
    getType (SReturnTyped _ typ) = typ
    isTypeError tstm = getType tstm == (TSimple TypeError)
-}

-- LExpTyped LExp TypeSpec Integer Integer
-- LIdentTyped PIdent TypeSpec Integer Integer
instance Typed LExp where
    getType (LExpTyped _ typ _ _ ) = typ
    getLoc (LExpTyped _ _ loc _ ) = loc
    isTypeError tlexp = getType tlexp == (TSimple TypeError)
  