{-# LANGUAGE CPP #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif
{-# LANGUAGE FlexibleInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintGramm.
--   Generated by the BNF converter.

module PrintGramm where

import qualified AbsGramm
import Data.Char

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else ' ':s)

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsGramm.PIdent where
  prt _ (AbsGramm.PIdent (_,i)) = doc (showString i)

instance Print AbsGramm.PFloat where
  prt _ (AbsGramm.PFloat (_,i)) = doc (showString i)

instance Print AbsGramm.PInteger where
  prt _ (AbsGramm.PInteger (_,i)) = doc (showString i)

instance Print AbsGramm.PString where
  prt _ (AbsGramm.PString (_,i)) = doc (showString i)

instance Print AbsGramm.PChar where
  prt _ (AbsGramm.PChar (_,i)) = doc (showString i)

instance Print AbsGramm.Program where
  prt i e = case e of
    AbsGramm.Prog declarations -> prPrec i 0 (concatD [prt 0 declarations])

instance Print [AbsGramm.Declaration] where
  prt = prtList

instance Print AbsGramm.TypeSpec where
  prt i e = case e of
    AbsGramm.TSimple stype -> prPrec i 0 (concatD [prt 0 stype])
    AbsGramm.TPointer typespec -> prPrec i 0 (concatD [doc (showString "&"), prt 0 typespec])
    AbsGramm.TArray exp typespec -> prPrec i 0 (concatD [doc (showString "Array"), doc (showString "["), prt 0 exp, doc (showString "]"), doc (showString "("), prt 0 typespec, doc (showString ")")])

instance Print AbsGramm.SType where
  prt i e = case e of
    AbsGramm.SType_float -> prPrec i 0 (concatD [doc (showString "float")])
    AbsGramm.SType_int -> prPrec i 0 (concatD [doc (showString "int")])
    AbsGramm.SType_char -> prPrec i 0 (concatD [doc (showString "char")])
    AbsGramm.SType_string -> prPrec i 0 (concatD [doc (showString "string")])
    AbsGramm.SType_bool -> prPrec i 0 (concatD [doc (showString "bool")])
    AbsGramm.SType_null -> prPrec i 0 (concatD [doc (showString "null")])

instance Print AbsGramm.Declaration where
  prt i e = case e of
    AbsGramm.DecVar pident typespec -> prPrec i 0 (concatD [doc (showString "var"), prt 0 pident, doc (showString ":"), prt 0 typespec])
    AbsGramm.DefVar pident typespec exp -> prPrec i 0 (concatD [doc (showString "var"), prt 0 pident, doc (showString ":"), prt 0 typespec, doc (showString "="), prt 0 exp])
    AbsGramm.DefArray pident exps -> prPrec i 0 (concatD [doc (showString "var"), prt 0 pident, doc (showString "="), doc (showString "Array"), doc (showString "("), prt 0 exps, doc (showString ")")])
    AbsGramm.DefProc pident args body -> prPrec i 0 (concatD [doc (showString "def"), prt 0 pident, doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "="), prt 0 body])
  prtList _ [] = concatD []
  prtList _ [] = concatD []
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString "\n"), prt 0 xs]
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsGramm.Exp] where
  prt = prtList

instance Print AbsGramm.Body where
  prt i e = case e of
    AbsGramm.EBody exp -> prPrec i 0 (concatD [prt 0 exp])
    AbsGramm.BBody block -> prPrec i 0 (concatD [prt 0 block])

instance Print [AbsGramm.Arg] where
  prt = prtList

instance Print AbsGramm.Arg where
  prt i e = case e of
    AbsGramm.DArg pident type_ -> prPrec i 0 (concatD [prt 0 pident, doc (showString ":"), prt 0 type_])
  prtList _ [] = concatD []
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsGramm.Op where
  prt i e = case e of
    AbsGramm.Or -> prPrec i 1 (concatD [doc (showString "||")])
    AbsGramm.And -> prPrec i 2 (concatD [doc (showString "&&")])
    AbsGramm.Less -> prPrec i 4 (concatD [doc (showString "<")])
    AbsGramm.LessEq -> prPrec i 4 (concatD [doc (showString "<=")])
    AbsGramm.Greater -> prPrec i 4 (concatD [doc (showString ">")])
    AbsGramm.GreterEq -> prPrec i 4 (concatD [doc (showString ">=")])
    AbsGramm.Equal -> prPrec i 4 (concatD [doc (showString "==")])
    AbsGramm.NotEq -> prPrec i 4 (concatD [doc (showString "!=")])
    AbsGramm.Plus -> prPrec i 5 (concatD [doc (showString "+")])
    AbsGramm.Minus -> prPrec i 5 (concatD [doc (showString "-")])
    AbsGramm.Prod -> prPrec i 6 (concatD [doc (showString "*")])
    AbsGramm.Div -> prPrec i 6 (concatD [doc (showString "/")])
    AbsGramm.Mod -> prPrec i 6 (concatD [doc (showString "%")])
    AbsGramm.Pow -> prPrec i 7 (concatD [doc (showString "^")])

instance Print AbsGramm.Exp where
  prt i e = case e of
    AbsGramm.EArray exps -> prPrec i 0 (concatD [doc (showString "Array"), doc (showString "("), prt 0 exps, doc (showString ")")])
    AbsGramm.ENot exp -> prPrec i 2 (concatD [doc (showString "!"), prt 2 exp])
    AbsGramm.ENeg exp -> prPrec i 7 (concatD [doc (showString "-"), prt 8 exp])
    AbsGramm.EDeref exp -> prPrec i 8 (concatD [doc (showString "&"), prt 8 exp])
    AbsGramm.ERef exp -> prPrec i 8 (concatD [doc (showString "*"), prt 8 exp])
    AbsGramm.EInt pinteger -> prPrec i 8 (concatD [prt 0 pinteger])
    AbsGramm.EFloat pfloat -> prPrec i 8 (concatD [prt 0 pfloat])
    AbsGramm.EVar pident -> prPrec i 8 (concatD [prt 0 pident])
    AbsGramm.EChar pchar -> prPrec i 8 (concatD [prt 0 pchar])
    AbsGramm.EString pstring -> prPrec i 8 (concatD [prt 0 pstring])
    AbsGramm.ETrue -> prPrec i 8 (concatD [doc (showString "true")])
    AbsGramm.EFalse -> prPrec i 8 (concatD [doc (showString "false")])
    AbsGramm.EOp exp1 op exp2 -> prPrec i 0 (concatD [prt 8 exp1, prt 0 op, prt 8 exp2])
    AbsGramm.ETyped exp type_ -> prPrec i 0 (concatD [doc (showString "["), prt 0 exp, doc (showString ":"), prt 0 type_, doc (showString "]")])
    AbsGramm.EVarTyped pident type_ pinteger1 pinteger2 -> prPrec i 2 (concatD [doc (showString "["), prt 0 pident, doc (showString ":"), prt 0 type_, doc (showString ","), doc (showString "("), prt 0 pinteger1, doc (showString ","), prt 0 pinteger2, doc (showString ")"), doc (showString "]")])
  prtList _ [] = concatD []
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsGramm.Stm] where
  prt = prtList

instance Print AbsGramm.Type where
  prt i e = case e of
    AbsGramm.Type_float -> prPrec i 0 (concatD [doc (showString "float")])
    AbsGramm.Type_int -> prPrec i 0 (concatD [doc (showString "int")])
    AbsGramm.Type_char -> prPrec i 0 (concatD [doc (showString "char")])
    AbsGramm.Type_string -> prPrec i 0 (concatD [doc (showString "string")])
    AbsGramm.Type_bool -> prPrec i 0 (concatD [doc (showString "bool")])
    AbsGramm.Type_null -> prPrec i 0 (concatD [doc (showString "null")])

instance Print AbsGramm.Stm where
  prt i e = case e of
    AbsGramm.Decla declaration -> prPrec i 0 (concatD [prt 0 declaration])
    AbsGramm.Expr exp -> prPrec i 0 (concatD [prt 0 exp])
    AbsGramm.SBlock block -> prPrec i 0 (concatD [prt 0 block])
    AbsGramm.Assign pident exp -> prPrec i 0 (concatD [prt 0 pident, doc (showString "="), prt 0 exp])
    AbsGramm.While exp stm -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm])
    AbsGramm.If exp stm1 stm2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm1, doc (showString "else"), prt 0 stm2])
  prtList _ [] = concatD []
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print AbsGramm.Block where
  prt i e = case e of
    AbsGramm.DBlock stms -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stms, doc (showString "}")])

